apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: arquitectura-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: docker.io/library/product-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/productosdb

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
